/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#ffffff',
        card: '#ffffff',
        border: '#000000',
        foreground: '#000000',
        muted: '#f2f2f2',
        'muted-foreground': '#555555',
        accent: {
          DEFAULT: '#ff3000',
          hover: '#d62700',
          foreground: '#ffffff',
        },
        swiss: {
          red: '#ff3000',
          redHover: '#d62700',
          black: '#000000',
          white: '#ffffff',
          gray: '#f2f2f2',
          border: '#000000',
          darkgray: '#171717',
          muted: '#666666',
        },
        success: '#059669',
        warning: '#d97706',
        danger: '#ff3000',
        purple: '#6d28d9',
      },
      borderRadius: {
        none: '0px',
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '0px',
      },
      borderWidth: {
        DEFAULT: '1px',
        '0': '0px',
        '2': '2px',
        '3': '3px',
        '4': '4px',
        '8': '8px',
      },
      letterSpacing: {
        tightest: '-0.05em',
        tighter: '-0.035em',
        tight: '-0.02em',
        normal: '0',
        wide: '0.04em',
        wider: '0.08em',
        widest: '0.15em',
        ultra: '0.22em',
      },
      fontFamily: {
        sans: ['Inter', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
        mono: ['SFMono-Regular', 'Consolas', 'Liberation Mono', 'Menlo', 'monospace'],
      },
    },
  },
  plugins: [],
}
